language: generic
sudo: enabled
install:
  - sudo sed -i "s/xenial/focal/g" /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install -y octave octave-control octave-statistics

dist: xenial

notifications:
  email:
    - leo@robol.it
    - stefano.massei@epfl.ch

jobs:
  include:
    - name: "Unit Tests / HODLR / QR compression"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; pkg load statistics; addpath tests; hodlroption('compression', 'qr'); hodlr_RunAllTests;"
    - name: "Unit Tests / HODLR / SVD compression / 2-norm"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; pkg load statistics; addpath tests; hodlroption('compression', 'svd'); hodlr_RunAllTests;"
    - name: "Unit Tests / HODLR / QR compression / 2-norm / Frobenius norm"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; pkg load statistics; addpath tests; hodlroption('compression', 'qr'); hodlroption('norm', 'fro'); hodlr_RunAllTests;"
    - name: "Unit Tests / HODLR / SVD compression / Frobenius norm"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; pkg load statistics; addpath tests; hodlroption('compression', 'svd'); hodlroption('norm', 'fro'); hodlr_RunAllTests;"
    - name: "Unit Tests / HSS / QR compression"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; pkg load statistics; addpath tests; hssoption('compression', 'qr'); hss_RunAllTests;"
    - name: "Unit Tests / HSS / SVD compression"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; pkg load statistics; addpath tests; hssoption('compression', 'svd'); hss_RunAllTests;"
    - name: "Unit Tests / HSS / QR compression / Frobenius norm"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; pkg load statistics; addpath tests; hssoption('compression', 'qr'); hssoption('norm', 'fro'); hss_RunAllTests;"
    - name: "Unit Tests / HSS / SVD compression / Frobenius norm"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; pkg load statistics; addpath tests; hssoption('compression', 'svd'); hssoption('norm', 'fro'); hss_RunAllTests;"
    - name: "Unit Tests / HMATRIX / QR compression"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; pkg load statistics; addpath tests; hmatrixoption('compression', 'qr'); hmatrix_RunAllTests;"
    - name: "Unit Tests / HMATRIX / SVD compression"
      stage: unit tests
      script: octave --no-gui --eval "pkg load control; pkg load statistics; addpath tests; hmatrixoption('compression', 'svd'); hmatrix_RunAllTests;"
